
version: "3"
networks:
  observability-net:
    driver: bridge

services:
  service_a:
    build:
      context: ./service_a
    container_name: service_a
    environment:
      URL_SERVICE_B: http://service_b:8080
      REQUEST_NAME_OTEL: service-a-request
      URL_ZIPKIN: http://zipkin:9411
      COLLECTOR_URL: otel_collector:4317
      HTTP_PORT: :8082
    ports:
      - "8082:8082"
      - "8083:8083"
    depends_on:
      - zipkin
      - otel_collector
    networks:
      - observability-net

  service_b:
    build:
      context: ./service_b
    container_name: service_b
    environment:
      REQUEST_NAME_OTEL: service-b-request
      URL_ZIPKIN: http://zipkin:9411
      COLLECTOR_URL: otel_collector:4317
      HTTP_PORT: :8080
    ports:
      - "8080:8080"
      - "8084:8084"
    depends_on:
      - zipkin
      - otel_collector
    networks:
      - observability-net

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - observability-net

  otel_collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./.docker/tmp:/tmp
    ports:
      - "4317:4317"
    networks:
      - observability-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./.docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - observability-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - observability-net

  # logstash e filebeat removidos para simplificar a arquitetura

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - observability-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - observability-net

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.13.0
    container_name: filebeat
    volumes:
      - ./.docker/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./.docker/tmp/otel-logs.json:/tmp/otel-logs.json:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - observability-net