version: "3"

services:
  service_a:
    build:
      context: ./service_a
    container_name: service_a
    environment:
      URL_SERVICE_B: http://service_b:8080
      REQUEST_NAME_OTEL: service-a-request
      URL_ZIPKIN: http://zipkin:9411
      COLLECTOR_URL: otel_collector:4317
      HTTP_PORT: :8082
    ports:
      - "8082:8082"
    depends_on:
      - zipkin  

  service_b:
    build:
      context: ./service_b
    container_name: service_b
    environment:
      REQUEST_NAME_OTEL: service-b-request
      URL_ZIPKIN: http://zipkin:9411
      COLLECTOR_URL: otel_collector:4317
      HTTP_PORT: :8080
    ports:
      - "8080:8080"
    depends_on:
      - zipkin

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  otel_collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"