FROM prom/prometheus:latest
USER root
ENTRYPOINT ["/bin/sh", "-c", "chown -R nobody:nogroup /prometheus && exec prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"]
