
setup.template.name: "otel-logs"
setup.template.pattern: "otel-logs*"
filebeat.inputs:
  - type: filestream
    id: docker-filestream
    enabled: true
    paths:
      - /var/lib/docker/containers/4593b0c44d162d599b8b29de6743f3ff15cfaa0c18d1b6afa303746f5db1da76/4593b0c44d162d599b8b29de6743f3ff15cfaa0c18d1b6afa303746f5db1da76-json.log
    processors:
      - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "otel-logs"

setup.kibana:
  host: "kibana:5601"

logging:
  level: info
